### PR TITLE
[VAX-430] enforcing only lowercase names for columns

### PR DESCRIPTION
**Pull request by paulharter**

### CODE REVIEW

**Comment by define-null** [comment]
Ticket is missing

**Comment by balegas** [comment]
Can someone (@paulharter) please take action to close this? Open ticket, request review and/or hand-off to someone if necessary

**Comment by balegas** [comment]
Ticket for this is VAX-430.

**Comment by magnetised** [comment]
can you have a look @paulharter, thanks

**Review by paulharter — COMMENTED** [review]
looks good to me

**Pull request merged**
