### PR TITLE
Update config and fix config naming.

### PR DESCRIPTION
**Pull request by thruflo**
Support:

```sh
electric config update [--app APP] [--env ENV] [--migrations-dir PATH]
```

Fix naming to use `app` and `env` everywhere, including the `electric.json`. And update the README to match latest usage.

### CODE REVIEW

**Comment by thruflo** [comment]
Messed up the last commit: the "bump the version" commit actually also makes a breaking change to the bundle format to get rid of the named `data` import, so rather than:

```js
import { data as bundle } from '../migrations/dist'
```

We just have:

```js
import bundle from '../migrations/dist'
```

**Comment by icehaunter** [comment]
Please add `Closes VAX-###` into the PR body

**Comment by thruflo** [comment]
> Closes VAX-###

Relates to VAX-518 but doesn't close it without other PRs across repos.

**Review by icehaunter — APPROVED** [review]
I have not looked through `+4,826 −2,826` changes, but I did play around with updated commands locally. It seems to work. I've raised a couple of non-blocking concerns on Discord

**Pull request merged**
